### ISSUE TITLE
Customizable widget

### ISSUE THREAD

**Issue by tkowalczyk** [changelly/api-changelly#11]
From few days I am always getting following error while using your widget on my webpage:

![image](https://user-images.githubusercontent.com/1682564/43076998-6be82f8c-8e86-11e8-87f7-ad1e637c510d.png)

**Comment by changelly** [comment]
Hi @tkowalczyk, sorry for the late reply. Do you have any issues with your widget now?

**Comment by tkowalczyk** [comment]
Hi, I think this is working now but please follow this channel and monitor it for issues.

**Comment by changelly** [comment]
@tkowalczyk we defenetly need to fill the gap with issue monitoring. In case of emergency fill free to write to pro@changelly.com, contact with one of our managers directly, or write to our support using a widget at our website.
