### ISSUE TITLE
"Parameter from is invalid" error message

### ISSUE THREAD

**Issue by xirkle** [changelly/api-changelly#13]
Hi,

We're using your python example and it's giving us an error message. We doing this integration on a VPS and via our Telegram crypto wallet bot called Xirklebot.

You can see it here: https://t.me/xirklebot

"Parameter from is invalid"

Here's how we go this error message:
![image](https://user-images.githubusercontent.com/30379932/46921057-9a0ec900-cfc4-11e8-94fb-eb43e36b4415.png)

![image](https://user-images.githubusercontent.com/30379932/46921061-a6932180-cfc4-11e8-91ef-4381fca1ea1b.png)

What are we doing wrong? I appreciate your help. Thank you!

**Comment by changelly** [comment]
It's hard to say what's wrong from provided details. Please provide python snippet you are trying to use. The message means you did not pass "from" property at all.

**Comment by xirkle** [comment]
params={
    "from": "doge",
    "to": "eth",
    "address": "0xa7a7899d944fe658c4b0a1803bab2f490bd3849e",
    "amount": 1,
  }

**Comment by changelly** [comment]
Thank you, but could you please send execly the code you using, including serializing and sending the request part? There is no error in the code you have provided, maybe it is somewhere else.

**Comment by codingsett** [comment]
Here is the full code 

![photo_2018-10-17_02-30-46](https://user-images.githubusercontent.com/27306293/47053232-b07b7700-d1b4-11e8-89cd-b9687744070e.jpg)

**Comment by changelly** [comment]
Hello! Try to use that snippet to create request body

```python

message = {
    'jsonrpc': '2.0',
    'id': 1,
    'method': 'createTransaction',
    params: {
        "from": "doge",
        "to": "eth",
        "address": "0xa7a7899d944fe658c4b0a1803bab2f490bd3849e",
        "amount": 1,
    }
}

```

Your params is an array. It should be an object.

**Comment by codingsett** [comment]
Thanks it worked!

**Comment by xirkle** [comment]
We completed the integration and ran a successful exchange. However, why can't I see any API stats or why hasn't the conversions tab been updated under my affiliate dashboard account? It's all blank. Are those stats real-time or is there a delay? Thanks!

**Comment by xirkle** [comment]
Thank you for all of your help! Everything is working as planned.
