### ISSUE TITLE
message for socket.io

### ISSUE THREAD

**Issue by lihao6485** [changelly/api-changelly#14]
Hi, I would like to use socket.io to get latest exchange status on my client but I'm not sure what is the valid logon message. Currently I'm using the below message
```
socket.emit("subscribe", {
   "apiKey": apiKey,
   "sign": sign,
   "message": {
       "Login": {}
   }
});
```

I believe there should have some other required params. Do I need to include the params for getting exchange status and is there some required field in the login object? Please advice, Thanks.

**Comment by changelly** [comment]
Hello.

To get an exchange status through socket io interface you should subscribe to `status` event, there are no additional params needed to `subscribe`. Also that is valid `Login` message in a snippet you have provided. Also no additional params needed. Our api checks that your sign is valid, we does not realy care about object body.

**Comment by changelly** [comment]
Yes, you will be subscribed to all status change events by all transactions related to api keys, as you mentioned. It's not possible to subscribe by transactionId using the socket.io interface. There is json-rpc function `getStatus` which can be used to track status of individual transaction.

**Comment by lihao6485** [comment]
Understood. Thanks.
