### ISSUE TITLE
Not working with PHP - CURL

### ISSUE THREAD

**Issue by uday1283** [changelly/api-changelly#2]
Hi,
We are trying to implement the API using PHP & CURL but your library do not  have enough information about it ( **Only available in C# & Python** ).

Below is what we are trying but it is returning "**Unauthorized**" as response. Appreciate if you can share some sample codes in PHP also.

$API_URL = 'https://api.changelly.com';
$API_KEY = 'XXXXX';
$API_SECRET = 'XXXXX';

$message = array();
$message['jsonrpc'] = '2.0';
$message['method'] = 'getMinAmount';
$message['params'] = array('from' => 'BTC', 'to' => 'LTC');
$message['id'] =123456;
$data = json_encode($message);
$sign = hash_hmac('SHA512', $data, $API_SECRET);
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $API_URL);
curl_setopt($ch, CURLOPT_HEADER, false); 
curl_setopt($ch, CURLOPT_GET, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);    
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Accept: application/json",'Authorization:api-key: '.$API_KEY.':sign: '.$sign));

$final_result = curl_exec($ch); 
curl_close($ch);

print_r($final_result);

Thanks

**Comment by changelly** [comment]
Hey, feel free to check our [example](https://github.com/changelly/changelly-examples/blob/master/php/example.php)

**Comment by uday1283** [comment]
Excellent .. work like charm :) @changelly
