### ISSUE TITLE
HTTP 404 for AML/KYC Policy example dialog image URLS

### ISSUE THREAD

**Issue by AmkSk** [changelly/api-changelly#22]
Both links
https://github.com/changelly/api-changelly/blob/master/content/faq/ark-kyc-mobile.jpg
and
https://github.com/changelly/api-changelly/blob/master/content/faq/ark-kyc-desktop.jpg
do not exist (404 Error is returned).

**Comment by changelly** [comment]
Hi! Thank you. Links is fixed.

https://github.com/changelly/api-changelly/pull/23
