### ISSUE TITLE
Setup for iOS in Swift

### ISSUE THREAD

**Issue by jaymutzafi** [changelly/api-changelly#5]
Hi,

I'm working in swift and been trying to just set up a basic test to get and parse a response for `getCurrencies`. I know you haven't posted any iOS examples but I am hoping you still might be able to tell me what I am doing wrong.

I am using [SwCrypt](https://github.com/soyersoyer/SwCrypt) for the HMAC signing. 

After trying a few libraries for the http call and getting only a 100 error back I ended up I used a simple URLSession but all I manage to get is an "Unauthorized" error. One variation of the error seems to say _"JSON text did not start with array or object and option to allow fragments not set."_ but i suspect I am messing up the signing by not formatting something right. 

One error gives: "<NSHTTPURLResponse: 0x60000003c160> { URL: https://api.changelly.com/ } { Status Code: 401 }"

The other this:

Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
"Unauthorized"

Here is my code:

```
var json = Data()
        let parameters = ["jsonrpc": "2.0", "id": 1, "method": "getCurrencies", "params": []] as [String : Any]
        do {
            json = try JSONSerialization.data(withJSONObject: parameters, options: .prettyPrinted)
        }
        catch {   }
        let info = NSKeyedArchiver.archivedData(withRootObject: json)
        let key = NSKeyedArchiver.archivedData(withRootObject: apiSecret)
        let sign = CC.HMAC(info, alg: .sha512, key: key)
        let signString = String(describing: sign)
        let headers = ["api-key:" : apiKey, "sign:" : signString, "Content-type:" : "application/json"]
let url = URL(string: apiUrl)
        let request = NSMutableURLRequest(url: url! as URL)
        request.setValue(apiKey, forHTTPHeaderField: "api-key")
        request.setValue(signString, forHTTPHeaderField: "sign")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = jsondata

        request.httpMethod = "GET"
        
        let task = URLSession.shared.dataTask(with: request as URLRequest, completionHandler: { (data, response, error) in
            guard let data = data, error == nil else {
                print(error)                                 // some fundamental network error
                return
            }

            do {
                let responseObject = try JSONSerialization.jsonObject(with: data)
                print(responseObject)
            } catch let jsonError {
                print(jsonError)
                print(String(data: data, encoding: .utf8))   // often the `data` contains informative description of the nature of the error, so let's look at that, too
            }

        })
        task.resume() 
```
 

Either i am formatting the JSON wrong, or the conversation to type Data for the HMAC library is messing up something for the Sign. 

Any pointers would be appreciated. 

Thanks!

**Comment by changelly** [comment]
hi @jaymutzafi. Try to use POST request instead of GET. Hope it helps.

**Comment by jaymutzafi** [comment]
@changelly I forgot to mention I wasn't sure if it was POST or GET and I've tried both earlier. I am getting the same error with POST so it's something else. Any other thoughts?

**Comment by changelly** [comment]
@jaymutzafi try to run another exampes (for instance - node.js) and check sign in both cases. We don't work with iOS anyhow for now, but your code looks fine and correct.

**Comment by jaymutzafi** [comment]
I've now ran getCurrencies in both PHP and Node and they produce different signs. Even though both have the same parameters, keys, and use sha512.

**Comment by tJpADUNCcs** [comment]
@jaymutzafi 
Did you solve this problem? I am faced exactly the same problem ... :(
Guess it's a SHA issue?

KR

**Comment by jaymutzafi** [comment]
I solved one problem but still can't get it to work. I needed to convert it to Hex after the SHA512 hash.

**Comment by tJpADUNCcs** [comment]
I solved it! My SAH512 algorythm was buggy and I switched to this one, maybe it helps you as well...
`
import CommonCrypto

// Usage:
// let result = "test".hmac(key: "apiSecret")
extension String {
    
    func hmac(key: String) -> String {
        var digest = [UInt8](repeating: 0, count: Int(CC_SHA512_DIGEST_LENGTH))
        CCHmac(CCHmacAlgorithm(kCCHmacAlgSHA512), key, key.count, self, self.count, &digest)
        let data = Data(bytes: digest)
        return data.map { String(format: "%02hhx", $0) }.joined()
    }
}
`

**Comment by changelly** [comment]
@jaymutzafi did you figured what the problem was? do you need any help?

**Comment by changelly** [comment]
Closed due to inactivity. Feel free to reopen in case of any questions.

**Comment by jaymutzafi** [comment]
Sorry for the delay. No, I did not figure it out, I kind of gave up on this your API unfortunately.
