### ISSUE TITLE
API public server

### ISSUE THREAD

**Issue by elongl** [changelly/api-changelly#6]
I would like to know if there's a public API server, and if there is, how do I access it?
When heading to https://api.changelly.com/ I'm getting in response "Unauthorized".
Is there a server that I can make requests to, or do I have to set up my own web server?

**Comment by changelly** [comment]
@elongl Thanks for your interest in our service! Please check https://changelly.com/developers.

**Comment by worktarget** [comment]
"Unauthorized" in response I am getting when I am trying to fetch currencies or executing any other api code. That code was working before. In last few months, only difference was that I changed the domain / url of my application

**Comment by borovik96** [comment]
You should sign request with your api key, as described here [changelly.com/developers](changelly.com/developers)
