### ISSUE TITLE
adding new coin

### ISSUE THREAD

**Issue by jared201** [changelly/api-changelly#7]
hi,

how do i add new coin to your exchange? 

thanks!

**Comment by changelly** [comment]
*Hey, I'm Mark, head of Changelly product. Thanks for your interest in our
service! We keep looking for promising cryptos to be listed.First off, I
need to learn more about your company. Please fill in the form and check
the overview materials: https://goo.gl/forms/cVlP8mRq8033pIDA3
<https://goo.gl/forms/cVlP8mRq8033pIDA3>Looking forward to hearing more
about your coin!Regards, Mark *

**Comment by changelly** [comment]
Thanks for your interest in our service!

We keep looking for promising cryptos to be listed.

First off, we need to learn more about your company. 
Please fill in the form and check the overview materials:

https://goo.gl/forms/cVlP8mRq8033pIDA3

Looking forward to hearing more about your coin!

Regards, Changelly team.
