### ISSUE TITLE
Feature Request: get all currencies along with price data

### ISSUE THREAD

**Issue by gentlemanjohn** [changelly/api-changelly#8]
It would be nice if there was a method that would return all the currencies with price data.  It's kind of a pain to have to loop through the currency list and make a separate call for each to get the rate.

**Comment by changelly** [comment]
In our current api scheme rate is dynamic and depends on amount. We are working to make what you are asking for possbile, but for now `getExchangedAmound` method is the only option.

**Comment by changelly** [comment]
Also `getExchageAmount` have an ability to take an array of pairs to calculate amounts in a batch. We have updated the readme. Hope this information will be useful.
